apiVersion: v1
kind: Template
metadata:
  name: oc1
objects:
- apiVersion: v1
  kind: Pod
  metadata:
    name: oc11
  spec:
    containers:
    - env:
        - name: TZ
          value: America/Toronto
        - name: MYVAR
          value: taratatira
      image: 172.30.1.1:5000/myfirstproject/oc
      name: master
      ports:
      - containerPort: 6379
        protocol: TCP
parameters:
# run it with oc process -f oc.yaml | oc create -f -